spring:
  application:
    name: SubscriptionSoftware

  datasource:
    url: 'jdbc:mysql://localhost:3306/subscriptiondb'
    username: 'root'
    password: 'root'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: 'none'